/**
 * aiController.js
 * Handles AI-powered features (resume analysis, skill-gap suggestions,
 * opportunity matching, chat assistance, mock-interview evaluation) via
 * external LLM providers.
 *
 * NOTE: This file contains placeholder fetch functions for Gemini and Grok.
 * Wire in real API keys via .env (GEMINI_API_KEY, GROK_API_KEY) and adjust
 * endpoint/payload shapes to match the providers' current API specs before
 * going to production.
 */

// ---------- Placeholder: Google Gemini ----------
const fetchGeminiResponse = async (prompt) => {
  try {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error('GEMINI_API_KEY is not configured');
    }

    const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`;

    const response = await fetch(endpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [
          {
            parts: [{ text: prompt }],
          },
        ],
      }),
    });

    if (!response.ok) {
      const errText = await response.text();
      throw new Error(`Gemini API error: ${response.status} - ${errText}`);
    }

    const data = await response.json();
    const text =
      data?.candidates?.[0]?.content?.parts?.[0]?.text ||
      'No response generated by Gemini.';

    return { provider: 'gemini', text };
  } catch (error) {
    console.error('fetchGeminiResponse error:', error.message);
    throw error;
  }
};

// ---------- Placeholder: Grok (xAI) ----------
const fetchGrokResponse = async (prompt) => {
  try {
    const apiKey = process.env.GROK_API_KEY;
    if (!apiKey) {
      throw new Error('GROK_API_KEY is not configured');
    }

    const endpoint = 'https://api.x.ai/v1/chat/completions';

    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: 'grok-beta',
        messages: [{ role: 'user', content: prompt }],
        temperature: 0.7,
      }),
    });

    if (!response.ok) {
      const errText = await response.text();
      throw new Error(`Grok API error: ${response.status} - ${errText}`);
    }

    const data = await response.json();
    const text =
      data?.choices?.[0]?.message?.content || 'No response generated by Grok.';

    return { provider: 'grok', text };
  } catch (error) {
    console.error('fetchGrokResponse error:', error.message);
    throw error;
  }
};

// Generic dispatcher — tries preferred provider, falls back to the other
const getAIResponse = async (prompt, preferredProvider = 'gemini') => {
  const providers =
    preferredProvider === 'grok'
      ? [fetchGrokResponse, fetchGeminiResponse]
      : [fetchGeminiResponse, fetchGrokResponse];

  let lastError;
  for (const providerFn of providers) {
    try {
      return await providerFn(prompt);
    } catch (err) {
      lastError = err;
      continue;
    }
  }
  throw lastError || new Error('All AI providers failed');
};

// @desc    Analyze a student's resume/profile and suggest improvements
// @route   POST /api/ai/resume-analysis
// @access  Private (student)
const analyzeResume = async (req, res) => {
  try {
    const { resumeText, targetRole } = req.body;

    if (!resumeText) {
      return res.status(400).json({
        success: false,
        message: 'Please provide resume text to analyze',
      });
    }

    const prompt = `You are a career advisor for engineering/college students in India.
Analyze the following resume content${targetRole ? ` for the target role "${targetRole}"` : ''} and provide:
1. Three key strengths
2. Three areas for improvement
3. Missing skills to consider learning
Resume:
"""${resumeText}"""
Respond concisely in plain text with clear sections.`;

    const result = await getAIResponse(prompt, 'gemini');

    return res.status(200).json({
      success: true,
      analysis: result.text,
      provider: result.provider,
    });
  } catch (error) {
    console.error('analyzeResume error:', error.message);
    return res.status(503).json({
      success: false,
      message: 'AI service is currently unavailable. Please try again later.',
    });
  }
};

// @desc    Suggest a skill-gap learning path for the student
// @route   POST /api/ai/skill-gap
// @access  Private (student)
const suggestSkillGap = async (req, res) => {
  try {
    const { currentSkills = [], targetRole } = req.body;

    if (!targetRole) {
      return res.status(400).json({
        success: false,
        message: 'Please provide a target role',
      });
    }

    const prompt = `A student currently has these skills: ${currentSkills.join(', ') || 'none listed'}.
They are targeting the role: "${targetRole}".
List the top 5 missing skills they should learn next, ordered by priority, with a one-line reason for each.`;

    const result = await getAIResponse(prompt, 'gemini');

    return res.status(200).json({
      success: true,
      suggestions: result.text,
      provider: result.provider,
    });
  } catch (error) {
    console.error('suggestSkillGap error:', error.message);
    return res.status(503).json({
      success: false,
      message: 'AI service is currently unavailable. Please try again later.',
    });
  }
};

// @desc    General-purpose AI chat assistant
// @route   POST /api/ai/chat
// @access  Private
const chatAssistant = async (req, res) => {
  try {
    const { message, provider } = req.body;

    if (!message) {
      return res.status(400).json({
        success: false,
        message: 'Please provide a message',
      });
    }

    const result = await getAIResponse(message, provider || 'gemini');

    return res.status(200).json({
      success: true,
      reply: result.text,
      provider: result.provider,
    });
  } catch (error) {
    console.error('chatAssistant error:', error.message);
    return res.status(503).json({
      success: false,
      message: 'AI service is currently unavailable. Please try again later.',
    });
  }
};

// @desc    Evaluate a completed mock-interview transcript and score it
// @route   POST /api/ai/evaluate-interview
// @access  Private (student)
const evaluateInterview = async (req, res) => {
  try {
    const { transcript, targetRole } = req.body;

    if (!transcript) {
      return res.status(400).json({
        success: false,
        message: 'Please provide the interview transcript to evaluate',
      });
    }

    const prompt = `You are an experienced hiring manager reviewing a mock interview transcript${
      targetRole ? ` for the role "${targetRole}"` : ''
    }.
Transcript:
"""${transcript}"""
Provide structured, honest feedback with:
1. Overall impression (1-2 sentences)
2. Strengths (2-3 bullet points)
3. Areas to improve (2-3 bullet points)
4. A readiness score out of 10 with a one-line justification
Respond in plain text with clear section headers.`;

    const result = await getAIResponse(prompt, 'gemini');

    return res.status(200).json({
      success: true,
      evaluation: result.text,
      provider: result.provider,
    });
  } catch (error) {
    console.error('evaluateInterview error:', error.message);
    return res.status(503).json({
      success: false,
      message: 'AI service is currently unavailable. Please try again later.',
    });
  }
};

module.exports = {
  analyzeResume,
  suggestSkillGap,
  chatAssistant,
  evaluateInterview,
  fetchGeminiResponse,
  fetchGrokResponse,
};
